-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.4
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        language: system
        files: \.js$
        args: ['--fix', '--ignore-pattern=!.eslintrc.js']
