repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
-   repo: https://github.com/prettier/prettier
    sha: 1.10.2
    hooks:
    -   id: prettier
        name: prettier
        # Prettier runs on JavaScript as part of eslint
        exclude_types: [javascript]
        exclude: ^package\.json
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        language: system
        files: \.js$
        args: ['--fix', '--ignore-pattern=!.eslintrc.js']
