language: node_js

node_js:
  - "8"

before_install:
  - curl -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.6

cache:
  yarn: true

install:
  - make node_modules

script:
  - make test
