language: node_js

dist: trusty

node_js:
    - '8'

before_install:
    - curl -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH="$HOME/.yarn/bin:$PATH"
    - pyenv global 3.10

cache:
    yarn: true

install:
    - yarn

script:
    - make test
